export const HOME_ROUTE: string = "/"
export const LOGIN_ROUTE: string = "/login"
export const REGISTER_ROUTE: string = "/register"
export const FAVORITE_ROUTE: string = "/favorite"
export const ADVERTISMENT_ROUTE: string = "/advertisment"
export const PERSONAL_ROUTE: string = "/personal"
